### ISSUE TITLE
Conda UnsatisfiableError: The following specifications were found to be incompatible with your CUDA driver

### ISSUE THREAD

**Issue by KevinMusgrave** [KevinMusgrave/pytorch-metric-learning#55]
Fix the following conda errors (not sure if they are reproducible errors):

Windows:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==10.2=0
  - feature:|@/win-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

Linux:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1
```

**Comment by pjgoodall** [comment]
I am having similar problems on Ubuntu 18.04.v
flipping from Python > 3.7 to Python > 3.8 broke relationships between many packages.
Was I wrong to think 3.8 is now mainstream?
[conda_conflicts.txt](https://github.com/KevinMusgrave/pytorch-metric-learning/files/4561761/conda_conflicts.txt)

```
[...]
The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1
```

```
nvidia-smi  | grep Version
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
```

**Comment by KevinMusgrave** [comment]
@pjgoodall Have you come across this issue when installing other conda packages?

**Comment by pjgoodall** [comment]
I'm just rebuilding that environment with Python 3.7. WIlling to try any experiments you like.
The 3.7 config failed. There were some nvidia updates came through this-morning. Perhaps they are related. I will try a similar 3.7 config I was using yesterday and see if I can and rebuild it.

nvidia package updates:
``` log
| 2020-05-01 08:12:06 upgrade nvidia-settings:amd64 390.77-0ubuntu0.18.04.1 440.44-0ubuntu0.18.04.1                                      │
│2020-05-01 08:12:06 status half-configured nvidia-settings:amd64 390.77-0ubuntu0.18.04.1                                               │
│2020-05-01 08:12:06 status unpacked nvidia-settings:amd64 390.77-0ubuntu0.18.04.1                                                      │
│2020-05-01 08:12:06 status half-installed nvidia-settings:amd64 390.77-0ubuntu0.18.04.1                                                │
│2020-05-01 08:12:06 status half-installed nvidia-settings:amd64 390.77-0ubuntu0.18.04.1                                                │
│2020-05-01 08:12:06 status unpacked nvidia-settings:amd64 440.44-0ubuntu0.18.04.1                                                      │
│2020-05-01 08:12:06 status unpacked nvidia-settings:amd64 440.44-0ubuntu0.18.04.1                                                      │
│2020-05-01 08:12:06 configure nvidia-settings:amd64 440.44-0ubuntu0.18.04.1 <none>                                                     │
│2020-05-01 08:12:06 status unpacked nvidia-settings:amd64 440.44-0ubuntu0.18.04.1                                                      │
│2020-05-01 08:12:06 status unpacked nvidia-settings:amd64 440.44-0ubuntu0.18.04.1                                                      │
│2020-05-01 08:12:06 status half-configured nvidia-settings:amd64 440.44-0ubuntu0.18.04.1                                               │
│2020-05-01 08:12:06 status installed nvidia-settings:amd64 440.44-0ubuntu0.18.04.1     
```

**Comment by pjgoodall** [comment]
@KevinMusgrave 
Flipping between 3.7 and 3.8 in this environment.yml seems to cause the problem reliably.
Moving between variants with `conda env update --file ./environment.yml --prune`  

Went from 3.7 to a fail on 3.8, and back to success on 3.7. Have also tried creating environments from scratch, with apparently identical results.
A lot of conda solver computation trying to get to 3.8.
[environment.zip](https://github.com/KevinMusgrave/pytorch-metric-learning/files/4561896/environment.zip)

**Comment by KevinMusgrave** [comment]
That's strange, I'll try to look into this more when I get the time. Thanks for posting your findings!

**Comment by Hanros94** [comment]
Hi Kevin

I have the same problem as you, have you found the solution?

**Comment by KevinMusgrave** [comment]
I haven't gotten around to fixing this. For now, if you want to use this package inside conda, you'll have to do:
```python
conda install pip
pip install pytorch-metric-learning
```

**Comment by Hanros94** [comment]
Oh ok cheers for the information

**Comment by KevinMusgrave** [comment]
@Hanros94 Did pip installation work for you?

**Comment by KevinMusgrave** [comment]
@pjgoodall Python 3.8 vs 3.7 seems to be [an issue with other packages as well](https://github.com/conda-forge/spyder-feedstock/issues/72#issuecomment-581081100).

**Comment by Hanros94** [comment]
I'm not trying to install this specific package, I was just getting the same error. I'm using python 3.7.6

**Comment by KevinMusgrave** [comment]
@Hanros94 When you try to install this package, do you get the error?

**Comment by Hanros94** [comment]
which command do you want me to try?

**Comment by KevinMusgrave** [comment]
conda install pytorch-metric-learning -c metric-learning

**Comment by Hanros94** [comment]
I'm getting the same error as you:

 Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==8.0=0
  - feature:|@/win-64::__cuda==8.0=0

Your installed CUDA driver is: 8.0

**Comment by Hanros94** [comment]
my conda version is obviously earlier however I'm making use of anaconda prompt and python 3.7.6

**Comment by KevinMusgrave** [comment]
I see, that's a bummer. I was hoping it was a python 3.8 vs 3.7 issue. Unfortunately this is hard to debug because the error message is so cryptic.

**Comment by mick-d** [comment]
I had a similar error for a completely unrelated package (cf this [issue comment](https://github.com/nipy/heudiconv/issues/426#issuecomment-628196635)) and this turns out **not** related to CUDA. The reason was because one of the dependency was not available for `python 3.8` and had the constraint `python<3.8.0a0` (cf conda-forge/dcmstack-feedstock/issues/12).

So not sure this is the case for you but it may be that one of the dependency is not yet available for `python 3.8`.

**Comment by Hanros94** [comment]
Ok that sounds great, I'm using python 3.7.6 however.

**Comment by mick-d** [comment]
@Hanros94 I just meant that you may need a lower python version (not necessarily 3.7 instead of 3.8).

However it turns out this is exactly the same situation. Your conda repo does not work with python 3.8 but it works with python 3.7 (more precisely 3.7.6), i just tested it:
```
conda create -n pml376 python=3.7.6
conda activate pml376
conda install pytorch-metric-learning -c metric-learning
```
Since 3.7.6 is the latest for python 3.7, you could also simply do:
```
conda create -n pml37 python=3.7
conda activate pml37
conda install pytorch-metric-learning -c metric-learning
```

**Comment by KevinMusgrave** [comment]
@mick-d Do you know if it matters which version of python I'm using when running conda-build? I'm using python 3.7.6.

**Comment by mick-d** [comment]
@KevinMusgrave Sorry i am not sure about conda-build, but i wouldn't be discard the python version angle as the problem can happen to `pytorch` itself as you can see from [this post](https://github.com/conda/conda/issues/9367#issuecomment-561147083)

**Comment by KevinMusgrave** [comment]
@mick-d I created a python 3.8 environment, then tried installing conda-build. Got this error:
```
The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.1=0

Your installed CUDA driver is: 10.1
```
Lmao!

[Looks like conda-build isn't ready for python 3.8](https://github.com/conda/conda-build/issues/3938), so I guess I'll have to wait to try that experient.

**Comment by KevinMusgrave** [comment]
I think I finally fixed it, and it was an error in the way I was building the package. 

For any other conda-building-noobs out there, here's what my **old** meta.yaml looked like:
```yaml
{% set name = "pytorch-metric-learning" %}
{% set version = "0.9.86" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "f7327b3314bfccf930c25ea47be78540730106a301ef12fd920a72defadd4247"

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
  run:
    - python >=3.0
    - numpy
    - scikit-learn
    - tqdm
    - pytorch
    - torchvision

about:
  home: "https://github.com/KevinMusgrave/pytorch-metric-learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch-metric-learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave
```


And here's what my **new** meta.yaml looks like:
```yaml
{% set name = "pytorch-metric-learning" %}
{% set version = "0.9.86" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f7327b3314bfccf930c25ea47be78540730106a301ef12fd920a72defadd4247

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - numpy
    - pip
    - python >=3.6
    - scikit-learn
    - pytorch
    - torchvision
    - tqdm
  run:
    - numpy
    - python >=3.6
    - scikit-learn
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - pytorch_metric_learning
    - pytorch_metric_learning.losses
    - pytorch_metric_learning.miners
    - pytorch_metric_learning.regularizers
    - pytorch_metric_learning.samplers
    - pytorch_metric_learning.testers
    - pytorch_metric_learning.trainers
    - pytorch_metric_learning.utils

about:
  home: "https://github.com/KevinMusgrave/pytorch-metric-learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch-metric-learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave
```

The build command that worked is: ```conda-build -c pytorch $pkg```, which is what I was doing before. (The new build script can be found [here](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/conda_build/build-conda-package.sh)

The **old** installation command that failed was: 
```conda install pytorch-metric-learning -c metric-learning```

The **new** command that works is:
```conda install pytorch-metric-learning -c metric-learning -c pytorch```

I have tested this on Linux python 3.7 and 3.8.
