### ISSUE TITLE
Cuda driver incompatibility 

### ISSUE THREAD

**Issue by Hanros94** [KevinMusgrave/pytorch-metric-learning#97]
I'm trying to run a python script in Anaconda Prompt: e.g
python name.py

However I'm getting the following error: 

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==8.0=0

Your installed CUDA driver is: 8.0

Could someone please advise me on how to solve this problem?

**Comment by KevinMusgrave** [comment]
[Seems to be an issue with other packages as well](https://github.com/conda-forge/spyder-feedstock/issues/72#issuecomment-581081100). Something to do with python 3.8.

**Comment by KevinMusgrave** [comment]
I opened [an issue in the conda repo.](https://github.com/conda/conda/issues/9934)

**Comment by Hanros94** [comment]
Cheers for the response Kev, the issue however is that I'm using python 3.7.6

**Comment by KevinMusgrave** [comment]
I think I finally fixed it, and it was an error in the way I was building the package. 

For any other conda-building-noobs out there, here's what my **old** meta.yaml looked like:
```yaml
{% set name = "pytorch-metric-learning" %}
{% set version = "0.9.86" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "f7327b3314bfccf930c25ea47be78540730106a301ef12fd920a72defadd4247"

build:
  number: 0
  script: "python -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
  run:
    - python >=3.0
    - numpy
    - scikit-learn
    - tqdm
    - pytorch
    - torchvision

about:
  home: "https://github.com/KevinMusgrave/pytorch-metric-learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch-metric-learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave
```


And here's what my **new** meta.yaml looks like:
```yaml
{% set name = "pytorch-metric-learning" %}
{% set version = "0.9.86" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f7327b3314bfccf930c25ea47be78540730106a301ef12fd920a72defadd4247

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - numpy
    - pip
    - python >=3.6
    - scikit-learn
    - pytorch
    - torchvision
    - tqdm
  run:
    - numpy
    - python >=3.6
    - scikit-learn
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - pytorch_metric_learning
    - pytorch_metric_learning.losses
    - pytorch_metric_learning.miners
    - pytorch_metric_learning.regularizers
    - pytorch_metric_learning.samplers
    - pytorch_metric_learning.testers
    - pytorch_metric_learning.trainers
    - pytorch_metric_learning.utils

about:
  home: "https://github.com/KevinMusgrave/pytorch-metric-learning"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The easiest way to use deep metric learning in your application. Modular, flexible, and extensible. Written in PyTorch."
  doc_url: "https://kevinmusgrave.github.io/pytorch-metric-learning"
  dev_url: ""

extra:
  recipe-maintainers:
    - KevinMusgrave
```

The build command that works is: ```conda-build -c pytorch $pkg```, which is what I was doing before. (The new build script can be found [here](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/conda_build/build-conda-package.sh)

The **old** installation command that failed was: 
```conda install pytorch-metric-learning -c metric-learning```

The **new** command that works is:
```conda install pytorch-metric-learning -c metric-learning -c pytorch```

I have tested this on Linux python 3.7 and 3.8.
